### ISSUE TITLE
Expose partitions & allow navigation by specifying offsets

### ISSUE THREAD

**Issue by bocytko** [zalando-incubator/peek#1]
I would like to navigate through a given partition. For this, `peek` needs to:

- expose partitions incl. offsets (`/event-types/${event}/partitions` endpoint)
- allow to specify a start & end offset to navigate through partitions (equals to a combination of `head` & `tail`)

**Comment by tlossen** [comment]
you can set starting cursors now. do you really need to set end, though?

**Comment by bocytko** [comment]
Thanks, works as expected 👍
