### ISSUE TITLE
Allow overriding PEEK_HOME

### ISSUE THREAD

**Issue by bocytko** [zalando-incubator/peek#2]
The [location-independent](https://github.com/zalando-incubator/peek/commit/c6196b5019d5439d9ad626064b97971d60e0c4ed) `peek.sh` does not allow to easily override `PEEK_HOME`.

I should be able to load `peek` as follows:

```shell
export PEEK_HOME="$HOME/peek"
source "$PEEK_HOME/bin/peek.sh"
```

**Comment by tlossen** [comment]
(now you can just place peek anywhere.)
