### ISSUE TITLE
Peek returns nothing when using --cursors

### ISSUE THREAD

**Issue by youssefmamdouh** [zalando-incubator/peek#7]
I am trying to use this command on nakadi-staging and i get nothing:
peek -n 1 --cursors 0:000000000000000000 diamond.replay.sales-order-service.balance

using --info returns valid information for the event and lists the 8 partitions with valid offsets.

Thanks

**Comment by tlossen** [comment]
damn, looks like `--cursors` broke (again). i'll look into it.

**Comment by tlossen** [comment]
@youssefmamdouh should be working now. 

BTW, to read a partition from the beginning, you can omit the offset:

`peek --cursors 0 diamond.replay.sales-order-service.balance`
